####API接口
GET http://localhost:3000/api/apps/list

###
POST http://localhost:3000/api/apps/create
Content-Type: application/json

{
  "args": [
    "test2"
  ]
}

###
POST http://localhost:3000/api/apps/info
Content-Type: application/json

{
  "args": [
    "test2"
  ]
}

###
POST http://localhost:3000/api/apps/publish
Content-Type: application/json

{
  "args": [
    "test2"
  ]
}


####网关接口
###
//可用test.dev.localhost访问
//因为java域名解析问题，使用Dapp-Addr代替host
GET http://localhost:7001/@list?path=/
DApp-Addr: dev:test

###
GET http://localhost:7001/
DApp-Addr: dev:test

###
PUT http://localhost:7001/index.html
DApp-Addr: dev:test

Hello World!
Test Upload!