####API接口
GET {{host}}/api/ipfs/status

###
GET {{host}}/api/apps/list

###
POST {{host}}/api/apps/create
Content-Type: application/json

{
  "args": [
    "test2"
  ]
}

###
POST {{host}}/api/apps/info
Content-Type: application/json

{
  "args": [
    "test2"
  ]
}

###
POST {{host}}/api/apps/publish
Content-Type: application/json

{
  "args": [
    "test2"
  ]
}


####网关接口
###
//可用test.dev.localhost访问
//因为java域名解析问题，使用Dapp-Addr代替host
GET {{host}}/api/file/list?path=/
DApp-Addr: {{app}}

###
GET {{host}}/
DApp-Addr: {{app}}

###
GET {{host}}/../.metadata
DApp-Addr: {{app}}

###
PUT {{host}}/api/file/upload?path=/index.html
DApp-Addr: {{app}}

Hello World!
Test Upload2!{{$timestamp}}

###
POST {{host}}/api/file/delete?path=/index2.html
DApp-Addr: {{app}}

###
PUT {{host}}/api/file/upload?path=/index2.html&from=/index.html
DApp-Addr: {{app}}

####数据库接口
###
POST {{host}}/api/db/create
Content-Type: application/json
DApp-Addr: {{app}}

{
  "name": "test1",
  "type": "docstore",
  "access": "private"
}

### 插入数据
PUT {{host}}/api/db/test1
Content-Type: application/json
DApp-Addr: {{app}}

{
  "_id": "a3",
  "otherKey": 123456,
  "desc": "test"
}

### 查询所有数据
GET {{host}}/api/db/test1
Content-Type: application/json
DApp-Addr: {{app}}

### 获取数据
GET {{host}}/api/db/test1/a3
Content-Type: application/json
DApp-Addr: {{app}}

### 删除数据
DELETE {{host}}/api/db/test1/a3
Content-Type: application/json
DApp-Addr: {{app}}