####数据库接口
@testdb= test1
###
POST {{host}}/api/dbs
Content-Type: application/json
DApp-Addr: {{appAddr}}

{
  "name": "{{testdb}}",
  "type": "docstore",
  "access": "private"
}

### 插入数据
@testDataId = a3
POST {{host}}/api/dbs/{{testdb}}
Content-Type: application/json
DApp-Addr: {{appAddr}}

{
  "_id": "{{testDataId}}",
  "otherKey": 123456,
  "desc": "test"
}

### 查询所有数据
GET {{host}}/api/dbs/{{testdb}}
Content-Type: application/json
DApp-Addr: {{appAddr}}

### 获取数据
GET {{host}}/api/dbs/{{testdb}}/{{testDataId}}
Content-Type: application/json
DApp-Addr: {{appAddr}}

### 删除数据
DELETE {{host}}/api/dbs/{{testdb}}/{{testDataId}}
Content-Type: application/json
DApp-Addr: {{appAddr}}