#### CID相关
###
POST {{host}}/ipfs/upload
Content-Type: text/plain

TEST FILE
###
GET {{host}}/ipfs/QmdE6ktvdpuXATuLgFumkRZcy9CqEXt3gdhVGYeUsmHRss/.txt

####网关接口
//可用test.dev.localhost访问
//因为java域名解析问题，使用Dapp-Addr代替host

###
GET {{host}}/
DApp-Addr: {{appAddr}}

###
GET {{host}}/@/.metadata
DApp-Addr: {{appAddr}}

###
GET {{host}}/api/file/list?path=/
DApp-Addr: {{appAddr}}

###
PUT {{host}}/api/file?path=/index.html
DApp-Addr: {{appAddr}}

###
PUT {{host}}/api/file?path=/index2.html&from=/index.html
DApp-Addr: {{appAddr}}

Hello World!
Test Upload!{{$localDatetime rfc1123}}

###
DELETE  {{host}}/api/file?path=/index2.html
DApp-Addr: {{appAddr}}