// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./components/Home.vue')['default'];
    NA: typeof import('naive-ui')['NA'];
    NButton: typeof import('naive-ui')['NButton'];
    NCard: typeof import('naive-ui')['NCard'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NDialog: typeof import('naive-ui')['NDialog'];
    NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
    NDivider: typeof import('naive-ui')['NDivider'];
    NForm: typeof import('naive-ui')['NForm'];
    NFormItem: typeof import('naive-ui')['NFormItem'];
    NFormItemCol: typeof import('naive-ui')['NFormItemCol'];
    NFormItemRow: typeof import('naive-ui')['NFormItemRow'];
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle'];
    NGrid: typeof import('naive-ui')['NGrid'];
    NGridItem: typeof import('naive-ui')['NGridItem'];
    NH1: typeof import('naive-ui')['NH1'];
    NIcon: typeof import('naive-ui')['NIcon'];
    NImage: typeof import('naive-ui')['NImage'];
    NInput: typeof import('naive-ui')['NInput'];
    NList: typeof import('naive-ui')['NList'];
    NListItem: typeof import('naive-ui')['NListItem'];
    NModal: typeof import('naive-ui')['NModal'];
    NP: typeof import('naive-ui')['NP'];
    NPageHeader: typeof import('naive-ui')['NPageHeader'];
    NSpace: typeof import('naive-ui')['NSpace'];
    NSpin: typeof import('naive-ui')['NSpin'];
    NTag: typeof import('naive-ui')['NTag'];
    NThing: typeof import('naive-ui')['NThing'];
    NUpload: typeof import('naive-ui')['NUpload'];
    PostView: typeof import('./components/PostView.vue')['default'];
    Setting: typeof import('./components/modals/Setting.vue')['default'];
  }
}

export {};
