// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./components/Home.vue')['default'];
    NButton: typeof import('naive-ui')['NButton'];
    NCard: typeof import('naive-ui')['NCard'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NDialog: typeof import('naive-ui')['NDialog'];
    NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
    NDivider: typeof import('naive-ui')['NDivider'];
    NDynamicTags: typeof import('naive-ui')['NDynamicTags'];
    NEmpty: typeof import('naive-ui')['NEmpty'];
    NForm: typeof import('naive-ui')['NForm'];
    NFormItem: typeof import('naive-ui')['NFormItem'];
    NFormItemRow: typeof import('naive-ui')['NFormItemRow'];
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle'];
    NH1: typeof import('naive-ui')['NH1'];
    NIcon: typeof import('naive-ui')['NIcon'];
    NImage: typeof import('naive-ui')['NImage'];
    NInput: typeof import('naive-ui')['NInput'];
    NList: typeof import('naive-ui')['NList'];
    NListItem: typeof import('naive-ui')['NListItem'];
    NModal: typeof import('naive-ui')['NModal'];
    NP: typeof import('naive-ui')['NP'];
    NPageHeader: typeof import('naive-ui')['NPageHeader'];
    NPagination: typeof import('naive-ui')['NPagination'];
    NSpace: typeof import('naive-ui')['NSpace'];
    NSpin: typeof import('naive-ui')['NSpin'];
    NTag: typeof import('naive-ui')['NTag'];
    NThing: typeof import('naive-ui')['NThing'];
    NTooltip: typeof import('naive-ui')['NTooltip'];
    NUpload: typeof import('naive-ui')['NUpload'];
    PostEdit: typeof import('./components/PostEdit.vue')['default'];
    PostView: typeof import('./components/PostView.vue')['default'];
    Setting: typeof import('./components/modals/Setting.vue')['default'];
  }
}

export {};
